### PR TITLE
UI estimated fee error #3505

### LINKED ISSUE #3505: UI estimated fee error
UI estimated fee error

UI fee calculation is wrong after OP number 40.

image

image

### PR DESCRIPTION
**Pull request by xiangxn**
<h2>Fix UI estimated fee error</h2>
Closes #3505

### CODE REVIEW

File: app/lib/common/trxHelper.js [hunk 1]
```diff
@@ -234,15 +234,29 @@ function estimateFee(op_type, options, globalObject, data = {}) {
         op_code,
         1
     ]);
-    /* Default to transfer fees if the op is missing in globalObject */
-    if (!currentFees)
-        currentFees = globalObject.getIn([
+
```
Comment (abitmore) [inline app/lib/common/trxHelper.js:237]: I guess we need to remove the above code? If the array is not continuous, for example, if fees of op 50 is not in the array, if to get fees of op 60 in such way, the fees of op 61 will be returned?

Comment (xiangxn) [reply app/lib/common/trxHelper.js]: Yes, there was a problem, I've fixed it

**Comment by sschiessl-bcp** [comment]
Good find, thanks!
