### PR TITLE
#2879 vesting balance loading

### LINKED ISSUE #2876: [2] Missing vesting balances
**Describe the bug**
The list displayed in the vesting balance page is incomplete.

For example, `temp-account` has these vesting balances:
```
locked >>> get_vesting_balances temp-account
[{
    "id": "1.13.24542",
    "owner": "1.2.4",
    "balance": {
      "amount": 136174,
      "asset_id": "1.3.113"
    },
    "policy": [
      2,{}
    ],
    "balance_type": "market_fee_sharing",
    "allowed_withdraw": {
      "amount": 136174,
      "asset_id": "1.3.113"
    },
    "allowed_withdraw_time": "2019-07-01T18:09:15"
  },{
    "id": "1.13.24648",
    "owner": "1.2.4",
    "balance": {
      "amount": 24,
      "asset_id": "1.3.121"
    },
    "policy": [
      2,{}
    ],
    "balance_type": "market_fee_sharing",
    "allowed_withdraw": {
      "amount": 24,
      "asset_id": "1.3.121"
    },
    "allowed_withdraw_time": "2019-07-01T18:09:15"
  }
]
```

**To Reproduce**
1. Go to 'https://develop.bitshares.org/#/account/temp-account/vesting'

**Expected behavior**
Data match.

**Screenshots**
image

### LINKED ISSUE #2879: Vesting Balance Loading
Here is a collection of faucet accounts

https://wallet.bitshares.org/#/account/onboarding.bitshares.foundation/vesting
https://wallet.bitshares.org/#/account/cryptobridge/vesting
https://wallet.bitshares.org/#/account/openledger/vesting
https://wallet.bitshares.org/#/account/onboarding-sparkdex/vesting
https://wallet.bitshares.org/#/account/btsabc.reg/vesting
https://wallet.bitshares.org/#/account/blckchnd/vesting
https://wallet.bitshares.org/#/account/gdex-faucet/vesting

The vesting balances have no loading indicator and the user does not know if it already has properly loaded. This issue is to show a loading indicator non-intrusive under the descriptive text as long as they are being loaded.

### PR DESCRIPTION
**Pull request by sschiessl-bcp**
<h2>General</h2>
Closes #2879
Closes #2876

Loads and re-renders reliably

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [ ] Check for unused code
- [ ] No unrelated changes are included
- [ ] None of the changed files are reformatting only
- [ ] Code is self explanatory or documented
- [ ] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [ ] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [ ] Dark
- [ ] Light
- [ ] Midnight

_Please provide screenshots/licecap of your changes below_

### CODE REVIEW

File: app/components/Account/AccountVesting.jsx [hunk 1]
```diff
@@ -163,7 +164,12 @@ class VestingBalance extends React.Component {
 
         if (vb) {
             balance = vb.balance.amount;
+            if (!balance) return null;
+
             cvbAsset = ChainStore.getAsset(vb.balance.asset_id);
```
Comment (startailcoon) [inline app/components/Account/AccountVesting.jsx]: Wouldn't it be better to use `FetchChainObjects` to fetch all vesting balances at the same time?

Comment (sschiessl-bcp) [reply app/components/Account/AccountVesting.jsx]: FetchChainObjects unfortunately also only does single fetches ... don't ask why ...

Comment (startailcoon) [reply app/components/Account/AccountVesting.jsx]: Oh, it just acts as an array parser. Didn't see that :|
