### PR TITLE
Issue 2906 - Updates to MyOpenOrders component

### LINKED ISSUE #2906: [2] My Open Orders and Settle Tabs does not update on Market Change
The same issue that was reported in https://github.com/bitshares/bitshares-ui/issues/2862 exists in the MyOpenOrders component that is used to render a users open orders and market settle orders.

This task is to apply the same fix to this component as done to the MarketHistory.

It will also handle code/view split.

### LINKED ISSUE #2965: [0.5] Incorrect settle orders data in exchanges page
**Describe the bug**

**To Reproduce**
1. Go to 'https://wallet.bitshares.org/#/market/BTS_CNY' (type URL in address bar)
2. Scroll down to 'settle orders'
image

3. click another market from the market list, e.g. BTS/bitusd
image

4. See error data in the page
image

### PR DESCRIPTION
**Pull request by startailcoon**
This PR does the following changes to the MyOpenOrders component

## Changelog
```
+ Code splitting with view/code
* Renames the component to `<MarketOrders />` to reflect the name of the similar component `<MarketHistory />`
* Fixes the PS issues, same as on #2862 
* Added key IDs
* Fixed missing update trigger on Settle Orders change
* Combined code to use same header both my orders and settle orders
```

Closes #2906 
Closes #2965

### CODE REVIEW

**Comment by sschiessl-bcp** [comment]
Renaming makes it impossible to review. Is there a "rename only" commit?

**Comment by sschiessl-bcp** [comment]
We also produced double efforts here (my fault, for lack of communication during travels). We wont claim bounty, but maybe interesting to see for you https://github.com/blockchainprojects/bitshares-ui/pull/149 ?

**Comment by startailcoon** [comment]
> Renaming makes it impossible to review. Is there a "rename only" commit?

I will make a few additional commits for you so you can see the changes for the file compared to the old one before renaming, making it easier to audit. 

Sorry to hear you had some double work on this, thought we where cleared on this when we spoke, but it happens. I'll review your changes and see if we have anything we could consider to be used.

**Comment by startailcoon** [comment]
I have reverted the name change to make it possible to audit the changes. A few minor fixes that was discovered where fixed in the process.

File: app/components/Exchange/MyOpenOrders.jsx [hunk 1]
```diff
@@ -558,133 +452,67 @@ class MyOpenOrders extends React.Component {
...
+            );
         }
 
+        let isSelected =
+            this.state.selectedOrders.length > 0 &&
+            this.state.selectedOrders.length == totalRows;
+
         return (
-            <div
+            <MarketsOrderView
```
Comment (sschiessl-bcp) [inline app/components/Exchange/MyOpenOrders.jsx]: not a big fan of this props abundance

File: app/components/Exchange/View/MarketOrdersView.jsx [hunk 2]
```diff
@@ -0,0 +1,237 @@
+import React from "react";
+import counterpart from "counterpart";
+import utils from "common/utils";
+import Translate from "react-translate-component";
+import PriceText from "../../Utility/PriceText";
+import AssetName from "../../Utility/AssetName";
+const rightAlign = {textAlign: "right"};
+import {Tooltip, Checkbox} from "bitshares-ui-style-guide";
+
+function MarketOrdersViewTableHeader({
```
Comment (sschiessl-bcp) [inline app/components/Exchange/View/MarketOrdersView.jsx]: Is there a specific reason you are not using actual components here?

Comment (startailcoon) [reply app/components/Exchange/View/MarketOrdersView.jsx]: In order to separate code and pure html components I decided to use stateless functions, as they don't need any of the React.Components functions. I did some reading on the topic and finally decided to do it this way. If there is even better ways to do this, I'm all ears.

File: app/components/Exchange/MyOpenOrders.jsx (hunk 1 above)
Comment (startailcoon) [reply app/components/Exchange/MyOpenOrders.jsx]: We used these many props before, moving the code to its own merely visualize this. We could bundle the props and just set them on the component though.

Comment (startailcoon) [reply app/components/Exchange/MyOpenOrders.jsx]: This seems to be an issue however. https://reactjs.org/docs/forwarding-refs.html

It doesn't have an issue on building locally, but it seems to be what breaks the current developer deployment?

https://github.com/bitshares/bitshares-ui/blob/42bf56bae0d13b7727c48c51d308b6e769a49c7d/app/components/Exchange/MyOpenOrders.jsx#L123

Comment (sschiessl-bcp) [reply app/components/Exchange/MyOpenOrders.jsx]: Yea, the view is not a component and has refs inside. This also breaks the encapsulation imo.

Make the view a class (doesn't have to be a component) and give it a proper event interface with regards to what events are possible for view manipulation

Comment (startailcoon) [reply app/components/Exchange/MyOpenOrders.jsx]: I've used this way, not really based on MVC separation recommendations, but for [this](https://programmingwithmosh.com/react/react-functional-components/). MVC separations can involve things like [Flux](https://github.com/facebook/flux).

The goal was to separate the HTML and SCSS code from the files that are getting very long at times. And since they didn't require, until this one, a class I was sticking to it. 

I can convert it to a class instead, and keep the new file structure, if you agree. I think it keeps the code easier to find in when the view parts are separated.

File: app/components/Exchange/View/MarketOrdersView.jsx (hunk 2 above)
Comment (sschiessl-bcp) [reply app/components/Exchange/View/MarketOrdersView.jsx]: > I'm all ears

This seams like a good read https://medium.com/of-all-things-tech-progress/understanding-mvc-architecture-with-react-6cd38e91fefd#apply-mvc-with-react-flux

Comment (startailcoon) [reply app/components/Exchange/View/MarketOrdersView.jsx]: Found that one as well, will dig into it and read what may work for us.

Comment (sschiessl-bcp) [reply app/components/Exchange/View/MarketOrdersView.jsx]: @gibbsfromncis He was all for sorting out business logic from view. Thoughts? Leading example?

**Comment by startailcoon** [comment]
@sschiessl-bcp ready for review/merging

**Comment by startailcoon** [comment]
If desired, we can revert the "view" style.

**Comment by sschiessl-bcp** [comment]
Can you post before and after shots plz?

**Comment by startailcoon** [comment]
> Can you post before and after shots plz?

Screenshots of the exchange, or something else?

**Comment by sschiessl-bcp** [comment]
> If desired, we can revert the "view" style.

Whatever you addressed with this comment :)

**Comment by startailcoon** [comment]
What I meant was that I could revert my code split to `/View/MarketOrdersView.jsx ` for this as we haven't yet decided on a practice. I'll revert these changes so we can merge the PR. It wouldn't make any visual changes that a screenshot would show though.

**Comment by sschiessl-bcp** [comment]
> What I meant was that I could revert my code split to `/View/MarketOrdersView.jsx ` for this as we haven't yet decided on a practice. I'll revert these changes so we can merge the PR. It wouldn't make any visual changes that a screenshot would show though.

Leave as is for now

**Comment by startailcoon** [comment]
Ok, anything else you want me to look look at or fix?

I feel this is done from my part.
