### PR TITLE
STAGING: Fix #1760 and AccountStoreBug

### LINKED ISSUE #1760: Send modal evaluates receiving account incorrectly
**Describe the bug**
blob:https://web.telegram.org/0934356d-2b6d-456c-a11a-b534d69cb18e

**To Reproduce**

1. Open https://wallet.bitshares.org/#/
2. Click transfer and enter any account that is not your own. The above unknwon account message will appear.
3. Delete last letter and retype it, and ta-da

I would recommend to push this onto staging and current release on Wednesday

### PR DESCRIPTION
**Pull request by sschiessl-bcp**
- fix #1760: Use FetchChain instead of direct getAccount
- fix bug in AccountStore: default passwordLogin may not exist in saved settings

Signed-off-by: Stefan Schiessl <stefan.schiessl@blockchainprojectsbv.com>

### CODE REVIEW

File: app/stores/AccountStore.js [hunk 1]
```diff
@@ -63,9 +65,7 @@ class AccountStore extends BaseStore {
             accountContacts: Immutable.Set(),
             linkedAccounts: Immutable.Set(), // linkedAccounts are accounts for which the user controls the private keys, which are stored in a db with the wallet and automatically loaded every time the app starts
             referralAccount,
-            passwordLogin: accountStorage.get("settings_v4", {
-                passwordLogin: true
-            }).passwordLogin
+            passwordLogin: settings.passwordLogin || true
```
Comment (svk31) [inline app/stores/AccountStore.js]: This will always return true, even if passwordLogin is set to false.

It should be done like this instead:
```
const storedSettings = ss.get("settings_v4", {passwordLogin: true});
this.state = {
    ...
   passwordLogin: storedSettings.passwordLogin
```

File: app/stores/WalletUnlockStore.js [hunk 2]
```diff
@@ -10,11 +10,10 @@ let ss = new ls(STORAGE_KEY);
...
         this.bindActions(WalletUnlockActions);
-        const storedSettings = ss.get("settings_v4");
-        let passwordLogin =
-            "passwordLogin" in storedSettings
-                ? storedSettings.passwordLogin
-                : true;
+
+        // can't use settings store due to possible initialization race conditions
+        const storedSettings = ss.get("settings_v4", {});
+        let passwordLogin = storedSettings.passwordLogin || true;
```
Comment (svk31) [inline app/stores/WalletUnlockStore.js]: Same as above, use this instead:

```
const storedSettings = ss.get("settings_v4", {passwordLogin: true});
this.state = {
    ...
   passwordLogin: storedSettings.passwordLogin
```
