### PR TITLE
On-chain powered Headline

### LINKED ISSUE #2679: On-chain powered Headline
**Describe the bug**
The UI needs a way to quickly inform users of ongoing issues or other important news. For that, a new component is to be implemented that hooks in on the very top of the screen and acts like a newsfeed. The content of it will be dynamically fetched from github.

Estimate 3

Tasks:
 - [ ] Implement component that fetches directly from github
 - [ ] Allow different types of notifications that are rendered differently
 - [ ] Information is displayed static on top, optionally as running feed 

EDIT: Switching to on-chain powered headline through description of TEST asset

### PR DESCRIPTION
**Pull request by sschiessl-bcp**
<h2>General</h2>
Closes #2679

Description of TEST asset is used for notifications.

We also added the possibility to add notifications via github, currently deactivated though. This is where significant amount of research was done.

Bounty requested for the task: 6

<h2>General</h2>
Please make sure the following is done:

- Pull request is onto develop
- If you haven't already, have a look at 
  - https://github.com/bitshares/bitshares-ui/blob/develop/CODE_OF_CONDUCT.md
  - https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md

<h2>Code Preparation</h2>

_Please review all your changes one last time before committing_

- [ ] Check for unused code
- [ ] No unrelated changes are included
- [ ] None of the changed files are reformatting only
- [ ] Code is self explanatory or documented
- [ ] All written text is properly translated (english language)

<h2>Testing</h2>

_The branch has been tested on the following browsers (desktop and mobile view)_

- [x] Chrome 
- [ ] Opera
- [ ] Firefox
- [ ] Safari

<h2>User interface changes</h2>

_Delete this section if there weren't any UI changes. Please make sure you tested your changes in all themes_

- [x] Dark
- [ ] Light
- [ ] Midnight

_Please provide screenshots/licecap of your changes below_

Screens see here https://github.com/bitshares/bitshares-ui/issues/2679#issuecomment-495212285

### CODE REVIEW

File: app/branding.js [hunk 1]
```diff
@@ -338,3 +338,7 @@ export function getAllowedLogins() {
     // possible: list containing any combination of ["password", "wallet"]
     return ["password", "wallet"];
 }
+
+export function getHeadFeedAsset() {
+    return ["TEST"];
```
Comment (abitmore) [inline app/branding.js]: Better check chain ID then use different asset. I'll create a new issue.
